pip_install_packages:
  - name: docker
docker_users:
  - "{{ vm_user }}"

# DataDog
datadog_config:
  logs_enabled: true
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Site
        url: http://127.0.0.1
network_config:
  enabled: true
