- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create varibales file
      ansible.builtin.template:
        src: "../templates/vars.j2"
        dest: ../../terraform/vars.auto.tfvars
      tags: 
      - plan
      - apply
    - name: Crate token
      ansible.builtin.shell:
        cmd: "yc iam create-token"
      register: token
      ignore_errors: yes
      tags: 
      - plan
      - apply
    - name: Plan
      ansible.builtin.shell:
        chdir: ../../terraform
        cmd: "terraform plan \
          -var 'yandex_token={{ token.stdout }}'"
      register: plan
      ignore_errors: yes
      tags: plan
    - name: Plan output
      ansible.builtin.debug:
        msg: "{{ plan.stdout_lines }}"
      tags: plan
    - name: Apply
      ansible.builtin.shell:
        chdir: ../../terraform
        cmd: "terraform apply \
          -var 'yandex_token={{ token.stdout }}'"
      register: apply
      ignore_errors: yes
      tags: apply
    - name: Apply output
      ansible.builtin.debug:
        msg: "{{ apply.stdout_lines }}"
      tags: apply
